services:
  postgres:
    # restart: always
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bingo

volumes:
  pgdata:
